# Generated by Django 4.0.4 on 2022-05-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_rename_question_que'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Que',
        ),
    ]
